---
- set_fact:
    mdc_oauth_client_secret: "{{ (ansible_date_time.epoch + mdc_namespace) | hash('sha512') }}"

- include_tasks: prereq.yml

- include_tasks: install-operator.yml

- include_tasks: install-console.yml

- include_tasks: install-oauth-client.yml