---
- name: Get mdc deployment config
  shell: "oc get dc/mdc -o json -n {{ mdc_namespace }}"
  register: mdc_get_dc_cmd

- name: patch mdc dc
  mdc_patch_manifest:
    env_var: MOBILE_SERVICES_CONFIG_FILE
    path: '/etc/mdc/servicesConfig.json'
    secret_name: manifest
    dc: "{{ mdc_get_dc_cmd.stdout|from_json }}"
  register: mdc_patch_dc

- name: Wirte new dc definition file
  copy:
    content: "{{ mdc_patch_dc.data }}"
    dest: "{{ mdc_template_dir }}/mdc.json"

- name: Apply dc changes
  shell: "oc apply -f {{ mdc_template_dir }}/mdc.json -n {{ mdc_namespace }}"

- name: Wait for mdc rollout
  shell: "oc rollout status dc/mdc -n {{ mdc_namespace }} --watch=false | grep 'rolled out'"
  register: result
  until: result.stdout
  retries: 50
  delay: 10
  failed_when: result.stderr
  changed_when: False