---
- name: Check if keycloak realm already exists
  shell: "oc get keycloakrealm/{{ rhsso_realm }} -n {{ rhsso_namespace }}"
  register: realm_cmd
  failed_when: realm_cmd.rc == 0

- name: Set template name if undefined
  set_fact:
    rhsso_realm_template: keycloak-clientless-realm.json.j2
  when: rhsso_realm_template is undefined

- name: Create realm template
  template:
    src: "{{ rhsso_realm_template }}"
    dest: "/tmp/keycloak-{{ rhsso_realm }}-realm.json"

- name: Seed evaluation users
  include: _inject_user.yml template="/tmp/keycloak-{{ rhsso_realm }}-realm.json" email={{ rhsso_seed_users_email_format|format(item|int) }} username={{ rhsso_seed_users_name_format|format(item|int)}} password={{ rhsso_seed_users_password }}
  with_sequence: count={{ rhsso_seed_users_count }}


- name: "Create keycloak realm resource"
  shell: "oc create -f /tmp/keycloak-{{ rhsso_realm }}-realm.json -n {{ rhsso_namespace }}"
  register: rhsso_kcr
  failed_when: rhsso_kcr.stderr != '' and 'AlreadyExists' not in rhsso_kcr.stderr
