---
enmasse_namespace: enmasse
enmasse_version: '0.24.1'
enmasse_multitenant: true
enmasse_enable_rbac: true
enmasse_api_server: true
enmasse_register_api_server: true
enmasse_service_catalog: true
enmasse_keycloak_admin_password: admin
enmasse_authentication_services: ["standard"]
enmasse_clean_artifacts: true
enmasse_enable_monitoring: false
enmasse_download_url: "https://github.com/EnMasseProject/enmasse/releases/download/{{ enmasse_version }}/enmasse-{{ enmasse_version }}.zip"
enmasse_beta_download_url: https://access.redhat.com/sites/default/files/announcements/install_and_examples_1.zip
enmasse_use_beta: false
enmasse_deploy_playbook_path: /ansible/playbooks/openshift/deploy_all.yml